pub use physics_core::constants::WEAPON_COUNT;
pub use physics_core::constants::{
    ARMOR_ABSORPTION, DAMAGE, DEFAULT_AMMO, FIRE_RATE, GAUNTLET_PLAYER_RADIUS, GAUNTLET_RANGE,
    GRENADE_HIT_GRACE, HITSCAN_PLAYER_RADIUS, MACHINE_RANGE, MAX_ARMOR, MAX_HEALTH, MEGA_HEALTH,
    PICKUP_AMMO, PICKUP_RADIUS, PLASMA_SPLASH_DMG, PLASMA_SPLASH_PUSH, PLASMA_SPLASH_RADIUS,
    QUAD_DURATION, QUAD_MULTIPLIER, RESPAWN_TIME, SELF_DAMAGE_REDUCTION, SELF_HIT_GRACE,
    SHOTGUN_PELLETS, SHOTGUN_RANGE, SHOTGUN_SPREAD, SPAWN_OFFSET_X, SPAWN_PROTECTION,
    SPLASH_RADIUS, WEAPON_ORIGIN_CROUCH_LIFT, WEAPON_PUSH,
};
pub use physics_core::constants::{PLAYER_HALF_H, TILE_H, TILE_W};

pub const DEFAULT_PORT: &str = "3001";
pub const DEFAULT_ROOM_ID: &str = "room-1";
pub const DEFAULT_MAP_NAME: &str = "dm2";
pub const DEFAULT_MAP_DIR: &str = "../public/maps";

pub const TICK_MILLIS: u64 = 16;
pub const SNAPSHOT_INTERVAL_TICKS: u64 = 2;
pub const OUTBOUND_CHANNEL_CAPACITY: usize = 64;
pub const ROOM_COMMAND_CAPACITY: usize = 1024;

pub const SNAPSHOT_BUFFER_RING: usize = 8;

pub const EXPLOSION_MID_BIAS: f32 = 40.0;
pub const EXPLOSION_MID_SCALE: f32 = 100.0;
pub const EXPLOSION_FAR_SCALE: f32 = 60.0;
pub const EXPLOSION_FAR_BIAS: f32 = 20.0;
